apiVersion: apps/v1
kind: Deployment
metadata:
  name: 2048-deployment
  labels:
    app: 2048-app
  namespace: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: 2048-app
  template:
    metadata:
      labels:
        app: 2048-app
    spec:
      containers:
      - name: 2048-container
        image: 455986776549.dkr.ecr.us-east-1.amazonaws.com/2048-app:5510c18eaa3af13455d330ba9da26bd0f20f5de5
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        ports:
        - containerPort: 3000
